# Generated by Django 3.2.7 on 2021-12-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
