# Generated by Django 3.2.7 on 2021-12-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
