# Generated by Django 3.2.7 on 2021-12-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0003_nurse_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='this_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='final_project_app.user'),
        ),
    ]
